version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms50m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
     - 5601:5601
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=patil9922
    ports:
      - 5432:5432
    restart: always
  app:
    depends_on:
      - elasticsearch
      - kibana
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DJANGO_SETTINGS_MODULE=logIngestor.settings
      - AWS_ACCESS_KEY=AKIARRH5S3ASID6QZMGY
      - AWS_SECRET_KEY=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
      - SQS_URL=https://sqs.eu-north-1.amazonaws.com/105758513188/log-ingestion-queue
      - DJANGO_DEBUG=True
volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local